In [3]:
import numpy as np

natural_numbers = np.arange(1,11)
print(natural_numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
import numpy as np

matrix = np.zeros((3,3))

print(matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np

matrix = np.random.randint(1, 11, size=(5, 5))

print(matrix)

[[ 3  8  2  6  3]
 [10  8  5  4  7]
 [ 3 10  1  2  3]
 [ 2  3  3 10 10]
 [ 6  5  8  2  5]]


In [6]:
import numpy as np

matrix = np.random.rand(4,4)

print(matrix)

[[0.29133764 0.94126051 0.6548791  0.7445637 ]
 [0.52627747 0.10060627 0.94045333 0.83680539]
 [0.55155529 0.65486523 0.50324534 0.58438161]
 [0.965548   0.68246078 0.37499528 0.38713718]]


In [7]:
import numpy as np

array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

print("Масив 1:", array1)
print("Масив 2:", array2)

addition_result = array1 + array2
print("Результат додавання:", addition_result)

subtraction_result = array1 - array2
print("Результат віднімання:", subtraction_result)

multiplication_result = array1 * array2
print("Результат множення:", multiplication_result)

Масив 1: [6 8 2 9 8]
Масив 2: [ 9 10  1  2 10]
Результат додавання: [15 18  3 11 18]
Результат віднімання: [-3 -2  1  7 -2]
Результат множення: [54 80  2 18 80]


In [8]:
import numpy as np

vector1 = np.random.rand(7)
vector2 = np.random.rand(7)

print(array1)
print(array2)

scalar = np.dot(vector1, vector2)
print(scalar)

[6 8 2 9 8]
[ 9 10  1  2 10]
1.2691663803004198


In [9]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

print(matrix1)
print(matrix2)

scalar = np.dot(matrix1,matrix2)
print(scalar)


[[10  4]
 [ 1  7]]
[[6 8 3]
 [9 6 7]]
[[ 96 104  58]
 [ 69  50  52]]


In [10]:
import numpy as np

matrix = np.random.randint(1,11, size=(3,3))

print(matrix)

reverse_matrix = np.linalg.inv(matrix)

print(reverse_matrix)

[[5 2 8]
 [2 7 2]
 [7 5 7]]
[[-0.33333333 -0.22222222  0.44444444]
 [ 0.          0.17948718 -0.05128205]
 [ 0.33333333  0.09401709 -0.26495726]]


In [11]:
import numpy as np

matrix = np.random.rand(4, 4)
print(matrix)

transposed_matrix = np.transpose(matrix)
print(transposed_matrix)

[[0.43088036 0.69567315 0.43387678 0.22690882]
 [0.35534709 0.43255467 0.90677179 0.86663282]
 [0.94733644 0.66629163 0.64969074 0.74773194]
 [0.1447764  0.23308949 0.26633643 0.39237458]]
[[0.43088036 0.35534709 0.94733644 0.1447764 ]
 [0.69567315 0.43255467 0.66629163 0.23308949]
 [0.43387678 0.90677179 0.64969074 0.26633643]
 [0.22690882 0.86663282 0.74773194 0.39237458]]


In [12]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)
print(matrix)
print(vector)

result = np.dot(matrix, vector)
print(result)

[[ 4  7  2  6]
 [ 4 10 10 10]
 [ 2  6  7  3]]
[10  3 10  4]
[105 210 120]


In [13]:
import numpy as np

matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
print(matrix)
print(vector)
result = np.dot(matrix, vector)
print(result)

[[0.30749939 0.80201081 0.49163669]
 [0.58726272 0.80825694 0.06972643]]
[0.61173273 0.29787205 0.65663887]
[0.7498318  0.64579006]


In [14]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
print(matrix1)
print(matrix2)

elementwise_matrix = np.multiply(matrix1, matrix2)
print(elementwise_matrix)

[[ 6  2]
 [ 9 10]]
[[6 9]
 [9 2]]
[[36 18]
 [81 20]]


In [15]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
print(matrix1)
print(matrix2)

matrix_product = np.dot(matrix1, matrix2)
print(matrix_product)

[[6 2]
 [4 4]]
[[ 5 10]
 [ 5  1]]
[[40 62]
 [40 44]]


In [16]:
import numpy as np

matrix = np.random.randint(1, 101, size=(5, 5))
print(matrix)

matrix_sum = np.sum(matrix)
print("\nСума елементів матриці:", matrix_sum)

[[70 20 30 22 61]
 [37 76 49 42 34]
 [55 77 34  5 64]
 [46 49 84 53  6]
 [34 13 74 60 96]]

Сума елементів матриці: 1191


In [17]:
import numpy as np

matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print(matrix1)
print(matrix2)

matrix_difference = matrix1 - matrix2
print(matrix_difference)

[[5 4 4 2]
 [7 9 3 2]
 [7 2 9 1]
 [4 6 4 8]]
[[6 8 2 6]
 [1 9 9 4]
 [7 7 8 8]
 [4 7 9 7]]
[[-1 -4  2 -4]
 [ 6  0 -6 -2]
 [ 0 -5  1 -7]
 [ 0 -1 -5  1]]


In [18]:
import numpy as np

matrix = np.random.rand(3, 3)
print(matrix)

row_sum_vector = np.sum(matrix, axis=1, keepdims=True)
print(row_sum_vector)

[[0.52593374 0.67002906 0.29612653]
 [0.94990013 0.62321223 0.96560817]
 [0.46250344 0.64899096 0.98725374]]
[[1.49208933]
 [2.53872053]
 [2.09874815]]


In [19]:
import numpy as np

matrix = np.random.randint(1, 11, size=(3, 4))
print(matrix)

squared_matrix = np.square(matrix)

print(squared_matrix)

[[ 5 10  2  3]
 [10  2  2  1]
 [ 4  7  5  4]]
[[ 25 100   4   9]
 [100   4   4   1]
 [ 16  49  25  16]]


In [20]:
import numpy as np

vector = np.random.randint(1, 51, size=4)
print(vector)
sqrt_vector = np.sqrt(vector)
print(sqrt_vector)

[37 42 22 24]
[6.08276253 6.4807407  4.69041576 4.89897949]
